### ISSUE TITLE
Global hotkeys

### ISSUE THREAD

**Issue by Nick6489** [mitchcapper/FSClient#1]
Despite your outstanding support for some keyboard shortcuts, the one thing missing is actual global hotkeys. This way, the softphone doesn't
have to get in a user's way every time a call comes in, we can hear the ring, take a call, and not leave our window. THis would be particularly useful in a radio environment, where a lot of work is done in various windows.

**Comment by mitchcapper** [comment]
I am open to this, I use a headset that has an answer/end call button so see the value.  What global hot keys would you want I would assume:
-Answer
-End Call
What else?

**Comment by Nick6489** [comment]
I can't remember, but does this support auto-conference on answer? Ultimately, if it does, all I'd care about is that the answer key would respect that setting. Upon further thought, Hold would probably be a nice hotkey, as well as transfer.

**Comment by mitchcapper** [comment]
No your feature request #2 for auto conference would cover that, i will respond there seperately.  We could add a hotkey however to conference in the call.  I am not sure how transfer would work (other than popping up the transfer box).   Global hot key binds of:
-Answer
-End Call
-Conference
-Hold
could be doable, although I am not sure if hold is better than mute and would like to limit the global hotkeys.

**Comment by Nick6489** [comment]
Ultimately, I don't think you necessarily have to bind the hotkeys by default, just so long as we had the options to create our own hotkeys. And yes, transfer would poop up the transfer dialogue.

**Comment by mitchcapper** [comment]
closing as dec0c0c finally added this support:)
