### ISSUE TITLE
MOH with multiple clients experiences rate playback issues

### ISSUE THREAD

**Issue by mjefim** [mitchcapper/FSClient#10]
Dear FSClient team,

we have isolated an issue, that is driving us crazy.

When we arrange a scenario in which the FSClient is sending multiple streams, the streams itself are not stable (dropping RTP packets actually). 

Scenario description: Accepting n calls and putting them on hold (with hold-music setup from local file), will result in hold music being played to the caller in a very slowed manner (n-times slower it seems). Interesting thing is that the active call does not experience same issue, audio is clear with the active call.

Can you give some feedback regarding the issue, is there anything we can do?

Kind Regards

**Comment by mitchcapper** [comment]
FSClient is best thought of as a UI on-top of freeswitch.  While it could be an FSClient config issue (see the fsxml for most of the config although some sofia items are set in the code).  Again fs_cli can be hooked up to FSClient directly to monitor.   The freeswitch consulting team is able to help troubleshoot issues in freeswitch, recreating the exact config FSClient uses in FS is also possible if desired (although debugging in FSClient directly should be enough).

I will leave this ticket open though, as it does sound like a bug overall that is:
Multiple calls put on hold that have a local MOH file with port audio slows the playback rate of each call down as more calls are put on hold.

That is the issue you are experiencing correct?

**Comment by mitchcapper** [comment]
Closing due to non response.
