### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by glaye** [mitchcapper/FSClient#12]
vs2015  .net 4.5.2
freeswitch 1.6.18

**Comment by glaye** [comment]
bindingexpreesion path error:'state' property not found on 'object' "StatusInfo' (HashCode=65602575)'. BindingExpression:Path=state; DateItem='StatusInfo'(HashCode=65602575); target element is 'TextBlock'(Name="); target property is 'Text'(type 'String')

**Comment by glaye** [comment]
“FSClient.vshost.exe”(CLR v4.0.30319: FSClient.vshost.exe): 已加载“C:\WINDOWS\Microsoft.Net\assembly\GAC_32\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“FSClient.vshost.exe”(CLR v4.0.30319: FSClient.vshost.exe): 已加载“C:\WINDOWS\assembly\GAC_MSIL\Microsoft.VisualStudio.HostingProcess.Utilities\14.0.0.0__b03f5f7f11d50a3a\Microsoft.VisualStudio.HostingProcess.Utilities.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“FSClient.vshost.exe”(CLR v4.0.30319: FSClient.vshost.exe): 已加载“C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“FSClient.vshost.exe”(CLR v4.0.30319: FSClient.vshost.exe): 已加载“C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“FSClient.vshost.exe”(CLR v4.0.30319: FSClient.vshost.exe): 已加载“C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“FSClient.vshost.exe”(CLR v4.0.30319: FSClient.vshost.exe): 已加载“C:\WINDOWS\assembly\GAC_MSIL\Microsoft.VisualStudio.HostingProcess.Utilities.Sync\14.0.0.0__b03f5f7f11d50a3a\Microsoft.VisualStudio.HostingProcess.Utilities.Sync.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“FSClient.vshost.exe”(CLR v4.0.30319: FSClient.vshost.exe): 已加载“C:\WINDOWS\assembly\GAC_MSIL\Microsoft.VisualStudio.Debugger.Runtime\14.0.0.0__b03f5f7f11d50a3a\Microsoft.VisualStudio.Debugger.Runtime.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“FSClient.vshost.exe”(CLR v4.0.30319: FSClient.vshost.exe): 已加载“E:\迅雷下载\fs_client\FSClient\bin\Debug\FSClient.vshost.exe”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“FSClient.vshost.exe”(CLR v4.0.30319: FSClient.vshost.exe): 已加载“C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework.Aero\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.Aero.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“FSClient.vshost.exe”(CLR v4.0.30319: FSClient.vshost.exe): 已加载“C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“FSClient.vshost.exe”(CLR v4.0.30319: FSClient.vshost.exe): 已加载“C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“FSClient.vshost.exe”(CLR v4.0.30319: FSClient.vshost.exe): 已加载“C:\WINDOWS\Microsoft.Net\assembly\GAC_32\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“FSClient.vshost.exe”(CLR v4.0.30319: FSClient.vshost.exe): 已加载“C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xaml\v4.0_4.0.0.0__b77a5c561934e089\System.Xaml.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“FSClient.vshost.exe”(CLR v4.0.30319: FSClient.vshost.exe): 已加载“C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml.Linq\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.Linq.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“FSClient.vshost.exe”(CLR v4.0.30319: FSClient.vshost.exe): 已加载“C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Data.DataSetExtensions\v4.0_4.0.0.0__b77a5c561934e089\System.Data.DataSetExtensions.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“FSClient.vshost.exe”(CLR v4.0.30319: FSClient.vshost.exe): 已加载“C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\UIAutomationProvider\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationProvider.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“FSClient.vshost.exe”(CLR v4.0.30319: FSClient.vshost.exe): 已加载“C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\UIAutomationTypes\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationTypes.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“FSClient.vshost.exe”(CLR v4.0.30319: FSClient.vshost.exe): 已加载“C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\WindowsBase\v4.0_4.0.0.0__31bf3856ad364e35\WindowsBase.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“FSClient.vshost.exe”(CLR v4.0.30319: FSClient.vshost.exe): 已加载“C:\WINDOWS\Microsoft.Net\assembly\GAC_32\PresentationCore\v4.0_4.0.0.0__31bf3856ad364e35\PresentationCore.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“FSClient.vshost.exe”(CLR v4.0.30319: FSClient.vshost.exe): 已加载“C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“FSClient.vshost.exe”(CLR v4.0.30319: FSClient.vshost.exe): 已加载“C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\mscorlib.resources\v4.0_4.0.0.0_zh-Hans_b77a5c561934e089\mscorlib.resources.dll”。模块已生成，不包含符号。
线程 0x3f0 已退出，返回值为 0 (0x0)。
线程 0x2e34 已退出，返回值为 0 (0x0)。
线程 0x1b14 已退出，返回值为 0 (0x0)。
程序“[9092] FSClient.vshost.exe: 程序跟踪”已退出，返回值为 0 (0x0)。
程序“[9092] FSClient.vshost.exe”已退出，返回值为 0 (0x0)。
“FSClient.vshost.exe”(CLR v4.0.30319: FSClient.vshost.exe): 已加载“C:\WINDOWS\Microsoft.Net\assembly\GAC_32\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“FSClient.vshost.exe”(CLR v4.0.30319: FSClient.vshost.exe): 已加载“C:\WINDOWS\assembly\GAC_MSIL\Microsoft.VisualStudio.HostingProcess.Utilities\14.0.0.0__b03f5f7f11d50a3a\Microsoft.VisualStudio.HostingProcess.Utilities.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“FSClient.vshost.exe”(CLR v4.0.30319: FSClient.vshost.exe): 已加载“C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“FSClient.vshost.exe”(CLR v4.0.30319: FSClient.vshost.exe): 已加载“C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“FSClient.vshost.exe”(CLR v4.0.30319: FSClient.vshost.exe): 已加载“C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“FSClient.vshost.exe”(CLR v4.0.30319: FSClient.vshost.exe): 已加载“C:\WINDOWS\assembly\GAC_MSIL\Microsoft.VisualStudio.HostingProcess.Utilities.Sync\14.0.0.0__b03f5f7f11d50a3a\Microsoft.VisualStudio.HostingProcess.Utilities.Sync.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“FSClient.vshost.exe”(CLR v4.0.30319: FSClient.vshost.exe): 已加载“C:\WINDOWS\assembly\GAC_MSIL\Microsoft.VisualStudio.Debugger.Runtime\14.0.0.0__b03f5f7f11d50a3a\Microsoft.VisualStudio.Debugger.Runtime.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“FSClient.vshost.exe”(CLR v4.0.30319: FSClient.vshost.exe): 已加载“E:\迅雷下载\fs_client\FSClient\bin\Debug\FSClient.vshost.exe”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“FSClient.vshost.exe”(CLR v4.0.30319: FSClient.vshost.exe): 已加载“C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework.Aero\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.Aero.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“FSClient.vshost.exe”(CLR v4.0.30319: FSClient.vshost.exe): 已加载“C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“FSClient.vshost.exe”(CLR v4.0.30319: FSClient.vshost.exe): 已加载“C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“FSClient.vshost.exe”(CLR v4.0.30319: FSClient.vshost.exe): 已加载“C:\WINDOWS\Microsoft.Net\assembly\GAC_32\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“FSClient.vshost.exe”(CLR v4.0.30319: FSClient.vshost.exe): 已加载“C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xaml\v4.0_4.0.0.0__b77a5c561934e089\System.Xaml.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“FSClient.vshost.exe”(CLR v4.0.30319: FSClient.vshost.exe): 已加载“C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml.Linq\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.Linq.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“FSClient.vshost.exe”(CLR v4.0.30319: FSClient.vshost.exe): 已加载“C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Data.DataSetExtensions\v4.0_4.0.0.0__b77a5c561934e089\System.Data.DataSetExtensions.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“FSClient.vshost.exe”(CLR v4.0.30319: FSClient.vshost.exe): 已加载“C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\UIAutomationProvider\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationProvider.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“FSClient.vshost.exe”(CLR v4.0.30319: FSClient.vshost.exe): 已加载“C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\UIAutomationTypes\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationTypes.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“FSClient.vshost.exe”(CLR v4.0.30319: FSClient.vshost.exe): 已加载“C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\WindowsBase\v4.0_4.0.0.0__31bf3856ad364e35\WindowsBase.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“FSClient.vshost.exe”(CLR v4.0.30319: FSClient.vshost.exe): 已加载“C:\WINDOWS\Microsoft.Net\assembly\GAC_32\PresentationCore\v4.0_4.0.0.0__31bf3856ad364e35\PresentationCore.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“FSClient.vshost.exe”(CLR v4.0.30319: FSClient.vshost.exe): 已加载“C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“FSClient.vshost.exe”(CLR v4.0.30319: FSClient.vshost.exe): 已加载“C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\mscorlib.resources\v4.0_4.0.0.0_zh-Hans_b77a5c561934e089\mscorlib.resources.dll”。模块已生成，不包含符号。
线程 0x2d10 已退出，返回值为 0 (0x0)。
线程 0x33d0 已退出，返回值为 0 (0x0)。
“FSClient.vshost.exe”(CLR v4.0.30319: FSClient.vshost.exe): 已加载“E:\迅雷下载\fs_client\FSClient\bin\Debug\FSClient.exe”。已加载符号。
“FSClient.vshost.exe”(CLR v4.0.30319: FSClient.vshost.exe): 已加载“C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“FSClient.vshost.exe”(CLR v4.0.30319: FSClient.vshost.exe): 已加载“E:\迅雷下载\fs_client\FSClient\bin\Debug\System.Windows.Controls.Input.Toolkit.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“FSClient.vshost.exe”(CLR v4.0.30319: FSClient.vshost.exe): 已加载“C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework.Aero2\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.Aero2.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“FSClient.vshost.exe”(CLR v4.0.30319: FSClient.vshost.exe): 已加载“E:\迅雷下载\fs_client\FSClient\bin\Debug\WPFToolkit.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“FSClient.vshost.exe”(CLR v4.0.30319: FSClient.vshost.exe): 已加载“C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework.resources\v4.0_4.0.0.0_zh-Hans_31bf3856ad364e35\PresentationFramework.resources.dll”。模块已生成，不包含符号。
“FSClient.vshost.exe”(CLR v4.0.30319: FSClient.vshost.exe): 已加载“C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationCore.resources\v4.0_4.0.0.0_zh-Hans_31bf3856ad364e35\PresentationCore.resources.dll”。模块已生成，不包含符号。
“FSClient.vshost.exe”(CLR v4.0.30319: FSClient.vshost.exe): 已加载“C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemXml\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemXml.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“FSClient.vshost.exe”(CLR v4.0.30319: FSClient.vshost.exe): 已加载“C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemXmlLinq\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemXmlLinq.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“FSClient.vshost.exe”(CLR v4.0.30319: FSClient.vshost.exe): 已加载“C:\Users\MrG\AppData\Local\Temp\VisualStudio.XamlDiagnostics.10616\WpfXamlDiagnosticsTap.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
“FSClient.vshost.exe”(CLR v4.0.30319: FSClient.vshost.exe): 已加载“C:\WINDOWS\assembly\GAC\Microsoft.VisualStudio.OLE.Interop\7.1.40304.0__b03f5f7f11d50a3a\Microsoft.VisualStudio.OLE.Interop.dll”。模块已生成，不包含符号。
“FSClient.vshost.exe”(CLR v4.0.30319: FSClient.vshost.exe): 已加载“E:\迅雷下载\fs_client\FSClient\bin\Debug\FreeSWITCH.Managed.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
线程 0x1e60 已退出，返回值为 0 (0x0)。
“FSClient.vshost.exe”(CLR v4.0.30319: FSClient.vshost.exe): 已加载“C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemCore\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemCore.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
System.Windows.Data Error: 40 : BindingExpression path error: 'state' property not found on 'object' ''StatusInfo' (HashCode=65602575)'. BindingExpression:Path=state; DataItem='StatusInfo' (HashCode=65602575); target element is 'TextBlock' (Name=''); target property is 'Text' (type 'String')
System.Windows.Data Error: 40 : BindingExpression path error: 'is_outgoing' property not found on 'object' ''StatusInfo' (HashCode=65602575)'. BindingExpression:Path=is_outgoing; DataItem='StatusInfo' (HashCode=65602575); target element is 'TextBlock' (Name=''); target property is 'Text' (type 'String')
System.Windows.Data Error: 40 : BindingExpression path error: 'duration' property not found on 'object' ''StatusInfo' (HashCode=65602575)'. BindingExpression:Path=duration; DataItem='StatusInfo' (HashCode=65602575); target element is 'TextBlock' (Name=''); target property is 'Text' (type 'String')
System.Windows.Data Error: 40 : BindingExpression path error: 'other_party_name' property not found on 'object' ''StatusInfo' (HashCode=65602575)'. BindingExpression:Path=other_party_name; DataItem='StatusInfo' (HashCode=65602575); target element is 'TextBlock' (Name=''); target property is 'Text' (type 'String')
“FSClient.vshost.exe”(CLR v4.0.30319: FSClient.vshost.exe): 已加载“E:\迅雷下载\fs_client\FSClient\bin\Debug\mod_managed.DLL”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
引发的异常:“System.AccessViolationException”(位于 mod_managed.DLL 中)
程序“[10616] FSClient.vshost.exe: 程序跟踪”已退出，返回值为 0 (0x0)。
程序“[10616] FSClient.vshost.exe”已退出，返回值为 -1 (0xffffffff)。

**Comment by mitchcapper** [comment]
I am closing this as I cannot repro if you can provide more steps that would be great.
