### ISSUE TITLE
Issues compiling the source

### ISSUE THREAD

**Issue by mjefim** [mitchcapper/FSClient#7]
Dear Mr. Capper,

we have been using FSClient as an integrated part of our solution for quite some time now, and we love it. A fact is that we are using an old version of your code to compile (from around 2012), since we ran into an issue I describe below, we tried to recompile the latest code but can not fix the dependencies to Freeswitch.Managed.dll, could you give us some pointers on how to proceed? We tried:
- use the .dlls from the installation on our computer, did not work
- tried to compile the freeswitch source, but for now have not been able to clone the repo due to access permissions

The issue we ran into: when we setup the hold music to a custom sound file and multiple calls are put on hold the hold music slows down. It seems that if n calls are on hold the hold music slows down n-times.

Thank you for your time, and a great project let me add.

**Comment by mitchcapper** [comment]
If you are having an issue building FreeSWITCH the git clone url should be: https://freeswitch.org/stash/scm/fs/freeswitch.git  and should not require any permissions / login.
The DLL's from the installer are from a very old version of FS and the entrypoint has changed.

My guess is the current FS version should fix that.
