### ISSUE TITLE
RTP no available candidates

### ISSUE THREAD

**Issue by mjefim** [mitchcapper/FSClient#8]
Dear mr. Capper,

thanks for the help on compiling the FSClient libraries, we have now successfully compiled and run the newest issue of FSClient.

We have encountered another problem whcih is, when a call is ringing we are unable to answer it because the FSClient core library is returning "no suitable candidates found" when searching for RTP candidates.
Here is the log showing the mentioned issue, INVITES are received successfully beforehand, so is the codec selection.
`
ee28f574-9e52-44eb-98c0-226c22cb250c 2017-04-06 11:30:27.964419 [DEBUG] switch_core_media.c:5018 Set telephone-event payload to 101@8000
ee28f574-9e52-44eb-98c0-226c22cb250c 2017-04-06 11:30:27.964419 [DEBUG] switch_core_media.c:3425 Set Codec sofia/softphone/031685460@172.19.1.55 PCMU/8000 20 ms 160 samples 64000 bits 1 channels
ee28f574-9e52-44eb-98c0-226c22cb250c 2017-04-06 11:30:27.964419 [DEBUG] switch_core_codec.c:111 sofia/softphone/031685460@172.19.1.55 Original read codec set to PCMU:0
ee28f574-9e52-44eb-98c0-226c22cb250c 2017-04-06 11:30:27.964419 [WARNING] switch_core_media.c:3813 NO candidate ACL defined, Defaulting to wan.auto
ee28f574-9e52-44eb-98c0-226c22cb250c 2017-04-06 11:30:27.964419 [DEBUG] switch_core_media.c:3843 Save audio Candidate cid: 1 proto: UDP type: host addr: 172.19.1.55:10864
ee28f574-9e52-44eb-98c0-226c22cb250c 2017-04-06 11:30:27.964419 [DEBUG] switch_core_media.c:3843 Save audio Candidate cid: 2 proto: UDP type: host addr: 172.19.1.55:10865
ee28f574-9e52-44eb-98c0-226c22cb250c 2017-04-06 11:30:27.964419 [DEBUG] switch_core_media.c:3885 Searching for rtp candidate.
ee28f574-9e52-44eb-98c0-226c22cb250c 2017-04-06 11:30:27.964419 [DEBUG] switch_core_media.c:3885 Searching for rtcp candidate.
ee28f574-9e52-44eb-98c0-226c22cb250c 2017-04-06 11:30:27.964419 [DEBUG] switch_core_media.c:3929 sofia/softphone/031685460@172.19.1.55 no suitable candidates found.
ee28f574-9e52-44eb-98c0-226c22cb250c 2017-04-06 11:30:27.964419 [DEBUG] switch_core_media.c:5361 Set telephone-event payload to 101@8000
ee28f574-9e52-44eb-98c0-226c22cb250c 2017-04-06 11:30:27.964419 [DEBUG] switch_core_media.c:5420 sofia/softphone/031685460@172.19.1.55 Set 2833 dtmf send payload to 101 recv payload to 101`

By Googling the issue we have found that this must be something in the ACL definitions, but are unable to fix it as there really is not much of a documentation concerning it.

We are thankfully awaiting Your response.

With best regards, Matic.

**Comment by mjefim** [comment]
Here is also the remote SDP which clearly contains two candidates:
`
ee28f574-9e52-44eb-98c0-226c22cb250c 2017-04-06 11:30:27.964419 [DEBUG] sofia.c:7257 Remote SDP:
ee28f574-9e52-44eb-98c0-226c22cb250c v=0
ee28f574-9e52-44eb-98c0-226c22cb250c o=- 1748897572 1748897572 IN IP4 172.19.1.55
ee28f574-9e52-44eb-98c0-226c22cb250c s=Asterisk
ee28f574-9e52-44eb-98c0-226c22cb250c c=IN IP4 172.19.1.55
ee28f574-9e52-44eb-98c0-226c22cb250c t=0 0
ee28f574-9e52-44eb-98c0-226c22cb250c m=audio 10864 RTP/AVP 0 8 97 101
ee28f574-9e52-44eb-98c0-226c22cb250c a=rtpmap:0 PCMU/8000
ee28f574-9e52-44eb-98c0-226c22cb250c a=rtpmap:8 PCMA/8000
ee28f574-9e52-44eb-98c0-226c22cb250c a=rtpmap:97 iLBC/8000
ee28f574-9e52-44eb-98c0-226c22cb250c a=fmtp:97 mode=30
ee28f574-9e52-44eb-98c0-226c22cb250c a=rtpmap:101 telephone-event/8000
ee28f574-9e52-44eb-98c0-226c22cb250c a=fmtp:101 0-16
ee28f574-9e52-44eb-98c0-226c22cb250c a=ice-ufrag:51507d0960d06bcd5b9ed57673e9bd30
ee28f574-9e52-44eb-98c0-226c22cb250c a=ice-pwd:6d8bc3eb25998ab40d3cc43e161a6c7f
ee28f574-9e52-44eb-98c0-226c22cb250c a=candidate:Hac130137 1 UDP 2130706431 172.19.1.55 10864 typ host
ee28f574-9e52-44eb-98c0-226c22cb250c a=candidate:Hac130137 2 UDP 2130706430 172.19.1.55 10865 typ host
ee28f574-9e52-44eb-98c0-226c22cb250c a=ptime:20
ee28f574-9e52-44eb-98c0-226c22cb250c a=maxptime:150`

**Comment by mitchcapper** [comment]
ACL items are normally warnings not the actual issue.   I suggest using fs_logger (or manually) posting the logs from both sides to pastebin where it would also be more readable.    I will close this but you can reply back below once you do so, although likely a FS issue not FSClient.  Also make sure your codecs are in sync.
