### ISSUE TITLE
RTP not sending after answering call

### ISSUE THREAD

**Issue by mjefim** [mitchcapper/FSClient#9]
Dear mr. Capper!

Thank You for all the help You've provided us, the last problem truly was in SDP encryption which our PBX providers enabled withouth telling us and have since fixed the issue.

Now we face a new problem, again. This time we do not hear the softphone voice in the cell phone that is calling, we can clearly hear the caller talking to us but the caller hears nothing. We have tried using the built in laptop speakers/microphone, a headset and different computers, but looking at the WireShark trace it seems like the RTP is only going one way. Untill we answer the call RTP packets are being sent from our local PC to the PBX, after answering it the RTP packets are comming to the local PC only.

I will include the WireShark trace and FreeSwitchClient log if that is of any help to You.

We are sorry to be bothering You this frequently but we are really unable to make any progress no matter what we try.

Thank You for Your help and input.

With regards, Matic.

EDIT: it seems were unable to attach .zip files, so we are using pastebin for the [FreeSwitch log](https://pastebin.com/mddX07rj), but I'm not sure how to send the WireShark trace in case it would be helpful to You.

**Comment by mitchcapper** [comment]
I suggest you contact consulting@freeswitch.org they would be happy to work with you on getting this fixed.

**Comment by mjefim** [comment]
Dear Mitch,

Thank you for directing us to the next step in our effort. I would just like to ask of one additional favor, would it be possible for you to send us your bundle of dlls needed by FSClient from the compile you were successful with?

Kind Regards,
